[build]
  command = "npm run build"
  # Do NOT set publish to ".next" manually, the plugin handles the output location.
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

# You can keep the Environment config if you need specific node versions
[build.environment]
  NODE_VERSION = "22"